# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'glovotest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for glovotest
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'SnapKit', '~> 4.0.0'
  pod 'ReactiveKit'
  pod 'Bond'

  target 'glovotestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'glovotestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
