//
//  MapInteractor.swift
//  glovotest
//
//  Created Jesús Solé on 15/12/2018.
//  Copyright © 2018 Jesús Solé. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import ReactiveKit

class MapInteractor: MapInteractorProtocol {

    weak var presenter: MapPresenterProtocol?
    var cities: [CityModel]!
    var citySelected: CityModel?
    var countries: [CountryModel]?
    
    func drawCitiesPolygons() {
        for city in cities {
            if let workingArea = city.workingArea {
                self.presenter?.drawCityPolygons(workingArea: workingArea)
            }
        }
    }
    
    func moveCameraToCityCenter() -> CityModel? {
        return self.citySelected
    }
}
