//
//  MapPresenter.swift
//  glovotest
//
//  Created Jesús Solé on 15/12/2018.
//  Copyright © 2018 Jesús Solé. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MapPresenter: MapPresenterProtocol {
    

    weak private var view: MapViewProtocol?
    var interactor: MapInteractorProtocol?
    private let router: MapWireframeProtocol

    init(interface: MapViewProtocol, interactor: MapInteractorProtocol?, router: MapWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func drawCitiesPolygons() {
        self.interactor?.drawCitiesPolygons()
    }
    
    func drawCityPolygons(cityCode: String, workingArea: [String]) {
        self.view?.drawCityPolygons(cityCode: cityCode, workingArea: workingArea)
    }
    
    func moveCameraToCityCenter() -> CityModel? {
        return self.interactor?.moveCameraToCityCenter()
    }
    
    func getCityOnPointInfo(point: CGPoint) {
        self.interactor?.getCityOnPointInfo(point: point)
    }
    
    func displayCityInfo(city: CityModel) {
        self.view?.displayCityInfo(city: city)
    }
    
    func getCitiesInfo() -> [CityModel]? {
        return self.interactor?.getCitiesInfo()
    }
}
