//
//  MapViewController.swift
//  glovotest
//
//  Created Jesús Solé on 15/12/2018.
//  Copyright © 2018 Jesús Solé. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import GoogleMaps
import SnapKit

class MapViewController: UIViewController, MapViewProtocol {

	var presenter: MapPresenterProtocol?
    
    var mapView: GMSMapView!

	override func viewDidLoad() {
        super.viewDidLoad()
        
        self.setup()
    }

    func setup() {
        self.mapView = GMSMapView()
        self.view.addSubview(self.mapView)
        
        self.mapView.snp.makeConstraints { (maker) in
            maker.width.height.equalTo(self.view)
        }
        
        MapManager.shared.loadMap(mapView: self.mapView)
        
        if let city = self.presenter?.moveCameraToCityCenter() {
            
        }
        
        self.drawCitiesPolygons()
    }
    
    func drawCitiesPolygons() {
        self.presenter?.drawCitiesPolygons()
    }
    
    func drawCityPolygons(workingArea: [String]) {
        MapManager.shared.createCityPolygons(inMap: self.mapView, polygonsPaths: workingArea)
    }
}
