//
//  CityListRouter.swift
//  glovotest
//
//  Created Jesús Solé on 16/12/2018.
//  Copyright © 2018 Jesús Solé. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CityListRouter: CityListWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(cities: [CityModel]) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CityListViewController(nibName: nil, bundle: nil)
        let interactor = CityListInteractor()
        let router = CityListRouter()
        let presenter = CityListPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        interactor.cities = cities
        
        return view
    }
    
    func presentMapModule(cities: [CityModel], citySelected: CityModel) {
        let mapController = MapRouter.createModule(cities: cities, citySelected: citySelected)
        self.viewController?.present(mapController, animated: true, completion: nil)
    }
}
