//
//  HomeInteractor.swift
//  glovotest
//
//  Created Jesús Solé on 12/12/2018.
//  Copyright © 2018 Jesús Solé. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeInteractor: HomeInteractorProtocol {

    weak var presenter: HomePresenterProtocol?
    
    func askForPermissions() {
        LocationManager.shared.askForPermissions { (granted) in
            if granted {
                
            } else {
                
            }
        }
    }
}
