//
//  HomePresenter.swift
//  glovotest
//
//  Created Jesús Solé on 12/12/2018.
//  Copyright © 2018 Jesús Solé. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePresenter: HomePresenterProtocol {

    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorProtocol?
    private let router: HomeWireframeProtocol

    init(interface: HomeViewProtocol, interactor: HomeInteractorProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func askForPermissions() {
        self.interactor?.askForPermissions()
    }

    func showMap(cities: [CityModel]) {
        self.router.presentMapModule(cities: cities)
    }
    
    func showCityList(cities: [CityModel]) {
        self.router.presentCityListModule(cities: cities)
    }
}
