//
//  HomeViewController.swift
//  glovotest
//
//  Created Jesús Solé on 12/12/2018.
//  Copyright © 2018 Jesús Solé. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import SnapKit

class HomeViewController: UIViewController, HomeViewProtocol {

	var presenter: HomePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        
        self.setup()
    }

    func setup() {
        let title = UILabel()
        title.text = "kGlovoTest".localize
        title.font = Fonts.homeTitle
        
        self.view.addSubview(title)
        title.snp.makeConstraints { (make) in
            make.center.equalTo(self.view)
        }
        
        self.presenter?.askForPermissions()
    }
    
    func showError() {
        AlertsManager.showAlertMessage(controller: self,
                                       title: "Error".localize,
                                       message: "ServerError".localize,
                                       buttonString: "Ok".localize)
    }
}
