//
//  HomeProtocols.swift
//  glovotest
//
//  Created Jesús Solé on 12/12/2018.
//  Copyright © 2018 Jesús Solé. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: class {
    func presentMapModule(cities: [CityModel])
    func presentCityListModule(cities: [CityModel])
}
//MARK: Presenter -
protocol HomePresenterProtocol: class {
    func askForPermissions()
    func showMap(cities: [CityModel])
    func showCityList(cities: [CityModel])
}

//MARK: Interactor -
protocol HomeInteractorProtocol: class {

    var presenter: HomePresenterProtocol?  { get set }
    func askForPermissions()
}

//MARK: View -
protocol HomeViewProtocol: class {

    var presenter: HomePresenterProtocol?  { get set }
}
