//
//  HomeInteractor.swift
//  glovotest
//
//  Created Jesús Solé on 12/12/2018.
//  Copyright © 2018 Jesús Solé. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import ReactiveKit

class HomeInteractor: HomeInteractorProtocol {

    weak var presenter: HomePresenterProtocol?
    
    func askForPermissions() {
        LocationManager.shared.askForPermissions { (granted) in
            self.getCities(checkCityLocation: granted)
        }
    }
    
    func getCities(checkCityLocation: Bool) {
        let cities = API.manager.getCities()
        let _ = cities.observeNext { cities in
            if checkCityLocation {
                var insideWorkingArea = false
                
                for city in cities {
                    if let workingArea = city.workingArea {
                        let result = MapManager.shared.isUserInsidePaths(polygonsPaths: workingArea)
                        if result {
                            insideWorkingArea = true
                        }
                        print("Is inside of ", city.code ?? "", " result = ", result)
                    }
                }
                
                if insideWorkingArea {
                    self.presenter?.showMap(cities: cities)
                } else {
                    self.presenter?.showCityList(cities: cities)
                }
            } else {
                self.presenter?.showCityList(cities: cities)
            }
        }
    }
}
